module.exports = {
    "identity": "Evaluacion_inicial",
    "connection": "estivTesting",
    "autoCreatedAt": false,
    "autoUpdatedAt": false,
    "attributes": {
        "id": {
            "type": "INTEGER",
            "primaryKey": "TRUE"
        },
        "Preg01": "INTEGER",
        "Preg02": "INTEGER",
        "Preg03": "INTEGER",
        "Preg04": "INTEGER",
        "Preg05": "STRING",
        "Preg06": "INTEGER",
        "Preg07": "INTEGER",
        "Preg08": "INTEGER",
        "Preg09": "INTEGER",
        "Preg10": "INTEGER",
        "Preg11": "STRING",
        "Preg12": "INTEGER",
        "Preg13": "INTEGER",
        "Preg14": "INTEGER",
        "Preg15": "INTEGER",
        "Preg16": "STRING",
        "Preg17": "INTEGER",
        "Preg18": "INTEGER",
        "Preg19": "INTEGER",
        "Preg20": "STRING",
        "Preg21": "INTEGER",
        "Preg22": "INTEGER",
        "Preg23": "INTEGER",
        "Preg24": "INTEGER",
        "Preg25": "INTEGER",
        "Preg26": "INTEGER",
        "Preg27": "INTEGER",
        "Preg28": "INTEGER",
        "Preg29": "INTEGER",
        "Preg30": "INTEGER",
        "Preg31": "INTEGER",
        "Preg32": "INTEGER",
        "Preg33": "INTEGER",
        "Preg34": "INTEGER",
        "Preg35": "INTEGER",
        "Preg36": "INTEGER",
        "Preg37": "INTEGER",
        "Preg38": "INTEGER",
        "createdAt": "DATE",
        "Evaluaciones": {
            "model": "Evaluaciones",
            "columnName": "evaluacion_id"
        }
    }
}